config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"


  resources :cocktails, only: [:index, :new, :show, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="form-add">
  <%= simple_form_for cocktail do |f| %>
    <%= f.input :name, class: "form-field" %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "add cocktail", class: "btn btn-info" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <% count = 0 %>
    <% @cocktails.each do |cocktail| %>
      <% count += 1 %>
      <div class="col-xs-12 col-sm-4">
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
              <% if cocktail.photo.blank? %>
                'https://source.unsplash.com/600x400/?cocktail/<%= count %>'
              <% else %>
                <%= cl_image_path cocktail.photo, height: 500, width: 500, crop: :fill, class: "show-image" %>
              <% end %>
          );">
            <div class="card-description">
              <%= cocktail.name %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="form-container">
    <h1>Add new cocktail</h1>
    <%= render "form", cocktail: @cocktail %>
    <%= link_to cocktails_path do %>
      <i class="far fa-arrow-alt-circle-left"></i>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="show-info">
        <h1><%= @cocktail.name %></h1>

        <h3>Ingredients</h3>
        <ul class="list-unstyled">
          <% @cocktail.doses.each do |dose| %>
            <li>
              <%= dose.description %>
              <%= dose.ingredient.name %>
              <%= link_to dose_path(dose), method: :delete, data: { confirm: "Remove dose?"} do %>
                <font size="-1"><i class="fas fa-trash-alt"></i></font>
              <% end %>
            </li>
          <% end %>
        </ul>

        <i id="add-form" class="fas fa-plus"></i>

        <div id="new-dose" style="display: none;">
          <%= render 'doses/form', cocktail: @cocktail, dose: @dose %>
        </div>

      </div>
    </div>
    <div class="col-xs-6">
      <% if @cocktail.photo.blank? %>
        <%= image_tag "https://source.unsplash.com/500x500/?alcohol", alt: "cocktail", class: "show-image" %>
      <% else %>
        <%= cl_image_tag @cocktail.photo, height: 500, width: 500, crop: :fill, class: "show-image" %>
      <% end %>
    </div>
    <%= link_to cocktails_path do %>
      <i class="far fa-arrow-alt-circle-left page-bottom"></i>
    <% end %>
  </div>
</div>

app/views/doses/_form.html.erb
<div class="form-add">
  <%= simple_form_for [cocktail, dose] do |f| %>
    <%= f.input :description, class: "form-field" %>
    <%= f.association :ingredient, class: "form-field" %>
    <%= f.submit "add dose", class: "btn btn-info" %>
  <% end %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="form-container">
    <h1>Add a new dose</h1>

    <%= render 'form', cocktail: @cocktail, dose: @dose %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>